# Import

In [1]:
from data_model.DataCleaner import DataCleaner
from dl_client import DatalakeClient
from tests_utils.manage_excel_support_file import *
import pandas as pd
import os

client = DatalakeClient()

# Controllo file caricati
## Serch for file

In [84]:
level = '3'

In [85]:
file_codes = ['ADNIMERGE', 'PTDEMOG', 'DXSUM', 'MMSE', 'ADAS', 'FAQ', 'CDR', 'MOCA', 'APOERES', 
            'UCSFFSX', 'UCSFFSX51', 'UCSFFSX6', 'UCSFFSX7', 'UCSFFSX51_ADNI1_3T', 'UCSFFSL51ALL', 'UCSFFSL51', 'UCSFFSL51Y1', 'UCSFFSL', 'UCSDVOL', 'UPENN_ROI_MARS']

In [86]:
# verifica file caricati
search = client.query_files(
    query={'custom.level' : 'cleaned_0'+level, 'custom.source' : 'ADNI', 'custom.file_code' : file_codes})
files = [x['filename'] for x in search['included_files']]
obj_name = [x['object_name'] for x in search['included_files']]
print(files)
print(obj_name)

['ADNIMERGE_25Jul2025_03.csv', 'MMSE_25Jul2025_03.csv', 'PTDEMOG_25Jul2025_03.csv', 'DXSUM_25Jul2025_03.csv', 'UCSFFSX7_11Aug2025_03.csv', 'UCSFFSX6_11Aug2025_03.csv', 'UCSFFSX51_11_08_19_11Aug2025_03.csv', 'UCSFFSX51_ADNI1_3T_02_01_16_11Aug2025_03.csv', 'UCSFFSX_11_02_15_11Aug2025_03.csv', 'UCSFFSL51ALL_08_01_16_11Aug2025_03.csv', 'UCSFFSL51_03_01_22_11Aug2025_03.csv', 'UCSFFSL51Y1_08_01_16_11Aug2025_03.csv', 'UCSFFSL_02_01_16_11Aug2025_03.csv', 'UCSDVOL_11Aug2025_03.csv', 'UPENNROI_MARS_06_01_16_09Oct2025_03.csv', 'APOERES_11Aug2025_03.csv', 'ADAS_28Oct2025_03.csv', 'FAQ_28Oct2025_03.csv', 'CDR_28Oct2025_03.csv', 'MOCA_28Oct2025_03.csv', 'UCSDVOL_28Oct2025_03.csv']
['cleaned/single_file/ADNIMERGE_25Jul2025_03.csv', 'cleaned/single_file/MMSE_25Jul2025_03.csv', 'cleaned/single_file/PTDEMOG_25Jul2025_03.csv', 'cleaned/single_file/DXSUM_25Jul2025_03.csv', 'cleaned/single_file/UCSFFSX7_11Aug2025_03.csv', 'cleaned/single_file/UCSFFSX6_11Aug2025_03.csv', 'cleaned/single_file/UCSFFSX51_11_08_19_11Aug2025_03.csv', 'cleaned/single_file/UCSFFSX51_ADNI1_3T_02_01_16_11Aug2025_03.csv', 'cleaned/single_file/UCSFFSX_11_02_15_11Aug2025_03.csv', 'cleaned/single_file/UCSFFSL51ALL_08_01_16_11Aug2025_03.csv', 'cleaned/single_file/UCSFFSL51_03_01_22_11Aug2025_03.csv', 'cleaned/single_file/UCSFFSL51Y1_08_01_16_11Aug2025_03.csv', 'cleaned/single_file/UCSFFSL_02_01_16_11Aug2025_03.csv', 'cleaned/single_file/UCSDVOL_11Aug2025_03.csv', 'cleaned/single_file/UPENNROI_MARS_06_01_16_09Oct2025_03.csv', 'cleaned/single_file/APOERES_11Aug2025_03.csv', 'cleaned/single_file/ADAS_28Oct2025_03.csv', 'cleaned/single_file/FAQ_28Oct2025_03.csv', 'cleaned/single_file/CDR_28Oct2025_03.csv', 'cleaned/single_file/MOCA_28Oct2025_03.csv', 'cleaned/single_file/UCSDVOL_28Oct2025_03.csv']

In [87]:
max = len(files)
i = 0
print(max)

21

In [ ]:
#i =8

In [ ]:
file_name =files[i]     #'UCSDVOL_28Oct2025_03.csv'
print(i, '---->', file_name)
if i < max-1:
    i += 1
    print('next: ', i, '\n\n')
else:
    print('last file', '\n\n')


metadata = client.get_metadata(object_name='cleaned/single_file/'+file_name)
display(metadata['metadata']['custom'])

20 ----> UCSDVOL_28Oct2025_03.csv
last file

{'cofattori': [],
 'file_code': 'UCSDVOL',
 'level': 'cleaned_03',
 'norm_intervallo': [],
 'norm_scala': [],
 'norm_scale_value': [],
 'norm_volume': ['Brain', 'ICV', 'Ventricles'],
 'population': ['ADNI1'],
 'predittori': ['Brain', 'ICV', 'Ventricles'],
 'source': 'ADNI',
 'volume_norm_values': {'Brain': [754149.98, 1244134.8, 'increasing'],
  'ICV': [1178000.0, 1950280.0, 'inverse'],
  'LHippocampus': [1866.23, 4715.54, 'inverse'],
  'Ventricles': [9942.24, 116400.08, 'increasing']}}

## Controll metadata

In [ ]:
'UCSFFSX', 'UCSFFSX51', 'UCSFFSX6'

## Download file searched

In [186]:
search = client.query_files(
    query={'custom.level' : 'cleaned_04', 'custom.source' : 'ADNI', 'custom.file_code': ['UCSFFSX', 'UCSFFSX51', 'UCSFFSX6', 'UCSFFSX7', 'UCSFFSX51_ADNI1_3T', 'UCSFFSL51ALL', 'UCSFFSL51', 'UCSFFSL51Y1', 'UCSFFSL', 'UCSDVOL', 'UPENN_ROI_MARS']})

zip_files = client.download_file(
    search['object_name'],  
    extract_zip=True)

df_new = zip_files[list(zip_files.keys())[10]].copy(deep=True)
print(list(zip_files.keys())[10])
df_new

UCSDVOL_28Oct2025_04.csv

,RID,VISCODE,VISIT_MONTH,EXAMDATE,STATUS,Brain%ICV,ICV%ICV,Ventricles%ICV,Hippocampus%ICV
0,2,sc,0,2005-08-26,complete,66.376611,100.0,6.495216,0.472903
1,3,sc,0,2005-09-01,complete,66.186512,100.0,5.107391,0.327410
2,3,m06,6,2006-03-13,complete,65.557551,100.0,5.331892,0.314240
3,3,m12,12,2006-09-12,complete,65.229907,100.0,5.488506,0.307518
4,3,m24,24,2007-09-12,complete,64.441220,100.0,6.029301,0.289132
...,...,...,...,...,...,...,...,...,...
2592,1425,m36,36,2010-08-16,complete,66.827458,100.0,2.003972,0.514626
2593,1427,sc,0,2007-08-20,complete,71.642369,100.0,1.494476,0.559996
2594,1430,sc,0,2007-09-07,complete,67.418097,100.0,2.258114,0.388360
2595,1430,m06,7,2008-04-04,complete,67.476466,100.0,2.324027,0.379025
2596,1435,sc,0,2007-09-07,complete,68.250611,100.0,2.797720,0.414954

In [137]:
print(list(zip_files.keys())[0])
df_1

UCSDVOL_11Aug2025_04.csv

,VISIT_MONTH,RID,EXAMDATE,STATUS,Brain%ICV,ICV%ICV,Ventricles%ICV,Hippocampus%ICV
0,0,2,2005-08-26,complete,66.376611,100.0,6.495216,0.472903
1,0,3,2005-09-01,complete,66.186512,100.0,5.107391,0.327410
2,6,3,2006-03-13,complete,65.557551,100.0,5.331892,0.314240
3,12,3,2006-09-12,complete,65.229907,100.0,5.488506,0.307518
4,24,3,2007-09-12,complete,64.441220,100.0,6.029301,0.289132
...,...,...,...,...,...,...,...,...
2592,36,1425,2010-08-16,complete,66.827458,100.0,2.003972,0.514626
2593,0,1427,2007-08-20,complete,71.642369,100.0,1.494476,0.559996
2594,0,1430,2007-09-07,complete,67.418097,100.0,2.258114,0.388360
2595,7,1430,2008-04-04,complete,67.476466,100.0,2.324027,0.379025
2596,0,1435,2007-09-07,complete,68.250611,100.0,2.797720,0.414954

In [151]:
result = client.delete_file(
    object_name="cleaned/single_file/UCSDVOL_11Aug2025_04.csv",
)

In [125]:
print(list(zip_files.keys())[1])
df_2

UCSDVOL_28Oct2025_01.csv

,RID,VISCODE,VISIT_MONTH,EXAMDATE,STATUS,Brain,ICV,Ventricles,LHippocampus,RHippocampus
0,2,sc,0,2005-08-26,complete,1225060,1845620,119877.0,4262.00,4466.00
1,3,sc,0,2005-09-01,complete,1131240,1709170,87294.0,3022.00,2574.00
2,3,m06,6,2006-03-13,complete,1120490,1709170,91131.1,2902.95,2467.94
3,3,m12,12,2006-09-12,complete,1114890,1709170,93807.9,2833.25,2422.75
4,3,m24,24,2007-09-12,complete,1101410,1709170,103051.0,2676.35,2265.41
...,...,...,...,...,...,...,...,...,...,...
2592,1425,m36,36,2010-08-16,complete,859635,1286350,25778.1,3306.14,3313.75
2593,1427,sc,0,2007-08-20,complete,1055070,1472690,22009.0,3907.00,4340.00
2594,1430,sc,0,2007-09-07,complete,793511,1177000,26578.0,1929.00,2642.00
2595,1430,m06,7,2008-04-04,complete,794198,1177000,27353.8,1892.61,2568.51
2596,1435,sc,0,2007-09-07,complete,1016470,1489320,41667.0,2722.00,3458.00

In [113]:
brain_icv_1_percentile = df_new['Brain%ICV'].quantile(0.01)
brain_icv_99_percentile = df_new['Brain%ICV'].quantile(0.99)
print("1st percentile of Brain%ICV:", brain_icv_1_percentile)
print("99th percentile of Brain%ICV:", brain_icv_99_percentile)

1st percentile of Brain%ICV: 60.165656607846906
99th percentile of Brain%ICV: 73.35712132349282

In [9]:
zip_files = client.download_file(
    search['object_name'],  
    extract_zip=True)

In [22]:
file = list(zip_files.keys())
print(file)

['UCSFFSL51ALL_08_01_16_11Aug2025_02.csv', 'UCSFFSL51_03_01_22_11Aug2025_02.csv', 'UCSFFSL51Y1_08_01_16_11Aug2025_02.csv', 'UCSFFSL_02_01_16_11Aug2025_02.csv']

In [27]:
file_name = file[3]

In [28]:
display(zip_files[file_name])

,VISIT_MONTH,RID,EXAMDATE,STATUS,LVentricle,ICV,LEntorhinal,LFusiform,LHippocampus,LMidTemp,RVentricle,REntorhinal,RFusiform,RHippocampus,RMidTemp
0,0,3,2005-09-01,complete,43506,1920690,1267,7995.0,2868,7947.0,28288,1084,8243.0,2328,10097
1,6,3,2006-03-13,complete,45405,1906430,1253,7395.0,2729,7707.0,29544,1104,7642.0,2247,10022
2,12,3,2006-09-12,complete,46164,1903820,1146,7021.0,2748,7615.0,29862,1024,7576.0,2267,9758
3,24,3,2007-09-12,complete,49933,1903420,1147,6943.0,2660,7074.0,32496,865,6795.0,2118,9237
4,0,4,2005-09-22,complete,19585,1679440,1981,10703.0,3228,8280.0,18872,1902,8787.0,3157,11263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3490,19,1427,2009-03-12,complete,11503,1560600,1837,7459.0,3582,9556.0,10319,1633,8488.0,3783,12160
3491,24,1427,2009-08-26,complete,10411,1525200,1856,7663.0,3450,9799.0,9483,1605,8567.0,3745,12400
3492,48,1427,2011-08-19,complete,11723,1488860,1653,7471.0,3468,9758.0,10669,1537,8254.0,3586,12131
3493,0,1430,2007-09-07,complete,11670,1216110,1144,6710.0,1684,5916.0,10963,1332,6345.0,2100,7313
3494,7,1430,2008-04-04,complete,12081,1220830,1140,7057.0,1791,6138.0,11468,1315,6628.0,2135,7414